export const LOAD_PAGE = 'LOAD_PAGE';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const UPDATE_CART = 'UPDATE_CART';
export const REQUEST_PRODUCT_LIST_PENDING = 'REQUEST_PRODUCT_LIST_PENDING';
export const REQUEST_PRODUCT_LIST_SUCCESS = 'REQUEST_PRODUCT_LIST_SUCCESS';
export const REQUEST_PRODUCT_LIST_FAILED = 'REQUEST_PRODUCT_LIST_FAILED';